# Generated by Django 2.1.7 on 2019-02-15 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('gos_nomer', models.CharField(max_length=6, verbose_name='Гос.номер')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Район')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_request', models.DateField(verbose_name='Дата заявки')),
                ('time_start_request', models.TimeField(verbose_name='Время подачи автомобиля')),
                ('time_end_request', models.TimeField(verbose_name='Длительность использования')),
                ('description', models.TextField(help_text='Пункт назначения, место подачи АТС, вид перевозки,цель поездки, характеристика груза, кол-во людей (указывать обязательно)')),
                ('comment', models.TextField(help_text='Примечания, Ф.И.О., номера удостоверений, дату проверки знаний, ответственных,стропальщиков и расстояние до крайнего провода ЛЭП(указывать обязательно)')),
                ('date_creater', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(blank=True, choices=[('n', 'новая'), ('c', 'рассмотрение'), ('r', 'отклонена'), ('a', 'согласована')], default='n', help_text='Состояние заявки', max_length=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Car', verbose_name='Автомобиль')),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Заявка на атотранспорт',
                'verbose_name_plural': 'Заявки на атотранспорт',
            },
        ),
        migrations.CreateModel(
            name='TypeCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_car', models.CharField(max_length=50, verbose_name='Тип АТС')),
            ],
        ),
        migrations.CreateModel(
            name='TypeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип заявки')),
            ],
        ),
        migrations.AddField(
            model_name='requests',
            name='type_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.TypeRequest', verbose_name='Тип заявки'),
        ),
        migrations.AddField(
            model_name='car',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.District', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='car',
            name='type_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.TypeCar', verbose_name='Тип АТС'),
        ),
    ]
