# Generated by Django 2.1.7 on 2019-02-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20190215_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='department',
        ),
        migrations.AddField(
            model_name='requests',
            name='department',
            field=models.ManyToManyField(related_name='departments', to='vehicles.Department', verbose_name='Подразделение(я)'),
        ),
    ]
