# Generated by Django 2.1.7 on 2019-02-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20190215_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Заявка на автотранспорт', 'verbose_name_plural': 'Заявки на автотранспорт'},
        ),
    ]
