# Generated by Django 2.1.7 on 2019-02-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20190215_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typecar',
            options={'verbose_name': 'Тип АТС', 'verbose_name_plural': 'Типы АТС'},
        ),
    ]
