# Generated by Django 2.1.7 on 2019-02-18 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20190215_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecar',
            old_name='type_car',
            new_name='name',
        ),
    ]
