# Generated by Django 2.1.7 on 2019-02-18 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20190218_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_model', to='vehicles.ModelCar', verbose_name='Марка АТС'),
        ),
        migrations.AlterField(
            model_name='car',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='vehicles.District', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_car', to='vehicles.TypeCar', verbose_name='Тип АТС'),
        ),
    ]
