# Generated by Django 2.1.7 on 2019-02-20 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_auto_20190218_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='department',
        ),
        migrations.AddField(
            model_name='requests',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='vehicles.Department', verbose_name='Подразделение(я)'),
            preserve_default=False,
        ),
    ]
