# Generated by Django 2.1.7 on 2019-02-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_auto_20190220_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requests',
            options={'ordering': ('date_creater',), 'verbose_name': 'Заявка на автотранспорт', 'verbose_name_plural': 'Заявки на автотранспорт'},
        ),
    ]
